### ISSUE TITLE
Systemd MACAddressPolicy configuration

### ISSUE THREAD

**Issue by jdubs** [Mellanox/network-operator#418]
**Why is this needed**:
We ran into an issue with ubutu20.04 regarding duplicate VF mac addresses when systemd's MACAddressPolicy is set to `persistent`. Since network operator will reconfigure mlnx devices we may also want to set this value too. This redhat bug report is very similar to what we experienced while deploying. https://bugzilla.redhat.com/show_bug.cgi?id=1751174

**What would you like to be added**:
Set systemd MACAddressPolicy=none if MACAddressPolicy=persistent & restart the network.

**Comment by adrianchiris** [comment]
Greetings !

As far as im aware, as long as you have a unique value in `/etc/machine-id` you should get a random and persistent MAC address for VFs when MACAddressPolicy is set to `persistent`.

trying it out on my setup, i was able to get duplicate MACs on VFs in two servers when MACAddressPolicy is set to persistent  when i set the value of `/etc/machine-id` to be the same on both (i just copied the value of one machine-id to the other) and VF netdevs are created with the same name on both machines.

restoring `/etc/machine-id` to its original (and different on both hosts) value, i then got unique MAC addresses.

In general, this file should have a unique value when the OS is installed on host.

> This redhat bug report is very similar to what we experienced while deploying. https://bugzilla.redhat.com/show_bug.cgi?id=1751174

I believe this bug root cause was that the same machine-id was used since it was a VM clone. can it be the same in your case ?

**Comment by adrianchiris** [comment]
currently network-operator does not handle machine specific configurations that should happen during boot.
if this decision changes, this can be re-evaluated.

although i do think this specific issue is should generally not happen and points to invalid initial configuration of the VM or BareMetal.
